### PR TITLE
Update the job posting questions index page

### PR DESCRIPTION
**Pull request by maxkaran**
## Proposed Change
Some minor changes to the suggested questions on the job posting questions index page.

### How did you do this?
Changed the HTML of the app/views/job_posting_questions/index.html.erb file.

### Why are you choosing this approach?
Updating the HTML is the only way I can think of!

### Any open questions you want to ask code reviewers?
Nope :)

### List of changes:

  - Reworded the 2 questions that are suggested on the page

## Pull Request Checklist:

  - [x] My submission passes all tests.
  - [x] I have lint my code locally prior to submission.
  - [x] I have written new tests for my core changes (where applicable).
Haven't written new tests as only HTML has been changed
  - [x] I have referenced all useful information (issues, tasks, etc) in the pull request.

### CODE REVIEW

**Review by RobertWSaunders — CHANGES_REQUESTED** [review]
This looks good now! 😄However, a couple of things that you can change in your PR description, see below:

- Make sure to use the imperative your commit messages and PR titles. 
  - If you were to change yours to be "Update the questions on a job posting questions index page" that would be the imperative. The key change is "Updated" to "Update". You can think of the imperative as telling someone to do something.
- Make sure to use proper markdown syntax for check boxes. See below for a comparison of what you did and what is better:

[ ✔️] This is what you did. 
- [x] This is what is better.

The reason this matters is because GitHub actually sees the checklist and will add some UI enhancements that make managing pull requests easier, see the image below: 

screen shot 2018-09-30 at 1 26 01 pm

- Try to keep your commit messages to be 50 characters, and instead add more detail into your commit descriptions. Look up the 50/72 rule for commits.

- The "Fixes:" in the PR template is purely to reference an issue number. For example, if you do "Fixes: #1000" then GitHub will actually parse it out and when the pull request merges the issue will be closed. GitHub has a couple of keywords that is works with, another one is "Closes". So if you don't have an issue to reference then just get rid of it. Also, we normally put the "Fixes" above your description.

- Also, see how at the bottom is says that your branch is not up to date with `dev`. That means that since you created your branch off of `dev` some more commits have made it to `dev` in that time, so your branch is no longer branched off of the head of `dev`. This is ok because there are no merge conflicts but it is best practice to make sure your branch is off of the most recent `dev` or `master`. So instead of pressing the `update` button at the bottom, on your local machine follow these steps:

- `git checkout dev` (checkout dev)

- `git pull` (update your dev branch)

- `git checkout html-updates` (checkout your branch)

- `git rebase dev` (rebase your branch onto the head of dev)

- `git push origin html-updates --force` (force push your branch to remote)

> NOTE: You might need to merge upstream into your dev if the changes to dev are from my repository.

Try to understand whats going on here as its important that you do. 

Ask questions here if you get stuck!

**Comment by RobertWSaunders** [comment]
Also, if you can, try to edit your commit message to use the imperative, hint, you can do this with `git rebase -i @~1` on your branch.

**Comment by maxkaran** [comment]
Thanks for the feedback! I have made the requested changes, take a look and let me know if I missed anything.

**Review by RobertWSaunders — APPROVED** [review]
Looks good to me! 🚀

**Pull request merged**
